/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedReviewsIndexRouteImport } from './routes/_authed/reviews/index'
import { Route as AuthedRequestsIndexRouteImport } from './routes/_authed/requests/index'
import { Route as AuthedPlacementsIndexRouteImport } from './routes/_authed/placements/index'
import { Route as AuthedManagersIndexRouteImport } from './routes/_authed/managers/index'
import { Route as AuthedApprenticesIndexRouteImport } from './routes/_authed/apprentices/index'
import { Route as AuthedApplicationsIndexRouteImport } from './routes/_authed/applications/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedReviewsNewRouteImport } from './routes/_authed/reviews/new'
import { Route as AuthedRequestsNewRouteImport } from './routes/_authed/requests/new'
import { Route as AuthedPlacementsNewRouteImport } from './routes/_authed/placements/new'
import { Route as AuthedPlacementsPlacementIdRouteImport } from './routes/_authed/placements/$placementId'
import { Route as AuthedApprenticesApprenticeIdRouteImport } from './routes/_authed/apprentices/$apprenticeId'
import { Route as AuthedApplicationsApplicationIdRouteImport } from './routes/_authed/applications/$applicationId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReviewsIndexRoute = AuthedReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRequestsIndexRoute = AuthedRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPlacementsIndexRoute = AuthedPlacementsIndexRouteImport.update({
  id: '/placements/',
  path: '/placements/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedManagersIndexRoute = AuthedManagersIndexRouteImport.update({
  id: '/managers/',
  path: '/managers/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedApprenticesIndexRoute = AuthedApprenticesIndexRouteImport.update({
  id: '/apprentices/',
  path: '/apprentices/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedApplicationsIndexRoute = AuthedApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedReviewsNewRoute = AuthedReviewsNewRouteImport.update({
  id: '/reviews/new',
  path: '/reviews/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRequestsNewRoute = AuthedRequestsNewRouteImport.update({
  id: '/requests/new',
  path: '/requests/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPlacementsNewRoute = AuthedPlacementsNewRouteImport.update({
  id: '/placements/new',
  path: '/placements/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPlacementsPlacementIdRoute =
  AuthedPlacementsPlacementIdRouteImport.update({
    id: '/placements/$placementId',
    path: '/placements/$placementId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedApprenticesApprenticeIdRoute =
  AuthedApprenticesApprenticeIdRouteImport.update({
    id: '/apprentices/$apprenticeId',
    path: '/apprentices/$apprenticeId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedApplicationsApplicationIdRoute =
  AuthedApplicationsApplicationIdRouteImport.update({
    id: '/applications/$applicationId',
    path: '/applications/$applicationId',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/profile': typeof AuthedProfileRoute
  '/applications/$applicationId': typeof AuthedApplicationsApplicationIdRoute
  '/apprentices/$apprenticeId': typeof AuthedApprenticesApprenticeIdRoute
  '/placements/$placementId': typeof AuthedPlacementsPlacementIdRoute
  '/placements/new': typeof AuthedPlacementsNewRoute
  '/requests/new': typeof AuthedRequestsNewRoute
  '/reviews/new': typeof AuthedReviewsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/applications/': typeof AuthedApplicationsIndexRoute
  '/apprentices/': typeof AuthedApprenticesIndexRoute
  '/managers/': typeof AuthedManagersIndexRoute
  '/placements/': typeof AuthedPlacementsIndexRoute
  '/requests/': typeof AuthedRequestsIndexRoute
  '/reviews/': typeof AuthedReviewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/profile': typeof AuthedProfileRoute
  '/applications/$applicationId': typeof AuthedApplicationsApplicationIdRoute
  '/apprentices/$apprenticeId': typeof AuthedApprenticesApprenticeIdRoute
  '/placements/$placementId': typeof AuthedPlacementsPlacementIdRoute
  '/placements/new': typeof AuthedPlacementsNewRoute
  '/requests/new': typeof AuthedRequestsNewRoute
  '/reviews/new': typeof AuthedReviewsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/applications': typeof AuthedApplicationsIndexRoute
  '/apprentices': typeof AuthedApprenticesIndexRoute
  '/managers': typeof AuthedManagersIndexRoute
  '/placements': typeof AuthedPlacementsIndexRoute
  '/requests': typeof AuthedRequestsIndexRoute
  '/reviews': typeof AuthedReviewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/applications/$applicationId': typeof AuthedApplicationsApplicationIdRoute
  '/_authed/apprentices/$apprenticeId': typeof AuthedApprenticesApprenticeIdRoute
  '/_authed/placements/$placementId': typeof AuthedPlacementsPlacementIdRoute
  '/_authed/placements/new': typeof AuthedPlacementsNewRoute
  '/_authed/requests/new': typeof AuthedRequestsNewRoute
  '/_authed/reviews/new': typeof AuthedReviewsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/applications/': typeof AuthedApplicationsIndexRoute
  '/_authed/apprentices/': typeof AuthedApprenticesIndexRoute
  '/_authed/managers/': typeof AuthedManagersIndexRoute
  '/_authed/placements/': typeof AuthedPlacementsIndexRoute
  '/_authed/requests/': typeof AuthedRequestsIndexRoute
  '/_authed/reviews/': typeof AuthedReviewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/profile'
    | '/applications/$applicationId'
    | '/apprentices/$apprenticeId'
    | '/placements/$placementId'
    | '/placements/new'
    | '/requests/new'
    | '/reviews/new'
    | '/api/auth/$'
    | '/applications/'
    | '/apprentices/'
    | '/managers/'
    | '/placements/'
    | '/requests/'
    | '/reviews/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/profile'
    | '/applications/$applicationId'
    | '/apprentices/$apprenticeId'
    | '/placements/$placementId'
    | '/placements/new'
    | '/requests/new'
    | '/reviews/new'
    | '/api/auth/$'
    | '/applications'
    | '/apprentices'
    | '/managers'
    | '/placements'
    | '/requests'
    | '/reviews'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/register'
    | '/_authed/dashboard'
    | '/_authed/profile'
    | '/_authed/applications/$applicationId'
    | '/_authed/apprentices/$apprenticeId'
    | '/_authed/placements/$placementId'
    | '/_authed/placements/new'
    | '/_authed/requests/new'
    | '/_authed/reviews/new'
    | '/api/auth/$'
    | '/_authed/applications/'
    | '/_authed/apprentices/'
    | '/_authed/managers/'
    | '/_authed/placements/'
    | '/_authed/requests/'
    | '/_authed/reviews/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reviews/': {
      id: '/_authed/reviews/'
      path: '/reviews'
      fullPath: '/reviews/'
      preLoaderRoute: typeof AuthedReviewsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/requests/': {
      id: '/_authed/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof AuthedRequestsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/placements/': {
      id: '/_authed/placements/'
      path: '/placements'
      fullPath: '/placements/'
      preLoaderRoute: typeof AuthedPlacementsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/managers/': {
      id: '/_authed/managers/'
      path: '/managers'
      fullPath: '/managers/'
      preLoaderRoute: typeof AuthedManagersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/apprentices/': {
      id: '/_authed/apprentices/'
      path: '/apprentices'
      fullPath: '/apprentices/'
      preLoaderRoute: typeof AuthedApprenticesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/applications/': {
      id: '/_authed/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof AuthedApplicationsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/reviews/new': {
      id: '/_authed/reviews/new'
      path: '/reviews/new'
      fullPath: '/reviews/new'
      preLoaderRoute: typeof AuthedReviewsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/requests/new': {
      id: '/_authed/requests/new'
      path: '/requests/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof AuthedRequestsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/placements/new': {
      id: '/_authed/placements/new'
      path: '/placements/new'
      fullPath: '/placements/new'
      preLoaderRoute: typeof AuthedPlacementsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/placements/$placementId': {
      id: '/_authed/placements/$placementId'
      path: '/placements/$placementId'
      fullPath: '/placements/$placementId'
      preLoaderRoute: typeof AuthedPlacementsPlacementIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/apprentices/$apprenticeId': {
      id: '/_authed/apprentices/$apprenticeId'
      path: '/apprentices/$apprenticeId'
      fullPath: '/apprentices/$apprenticeId'
      preLoaderRoute: typeof AuthedApprenticesApprenticeIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/applications/$applicationId': {
      id: '/_authed/applications/$applicationId'
      path: '/applications/$applicationId'
      fullPath: '/applications/$applicationId'
      preLoaderRoute: typeof AuthedApplicationsApplicationIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedApplicationsApplicationIdRoute: typeof AuthedApplicationsApplicationIdRoute
  AuthedApprenticesApprenticeIdRoute: typeof AuthedApprenticesApprenticeIdRoute
  AuthedPlacementsPlacementIdRoute: typeof AuthedPlacementsPlacementIdRoute
  AuthedPlacementsNewRoute: typeof AuthedPlacementsNewRoute
  AuthedRequestsNewRoute: typeof AuthedRequestsNewRoute
  AuthedReviewsNewRoute: typeof AuthedReviewsNewRoute
  AuthedApplicationsIndexRoute: typeof AuthedApplicationsIndexRoute
  AuthedApprenticesIndexRoute: typeof AuthedApprenticesIndexRoute
  AuthedManagersIndexRoute: typeof AuthedManagersIndexRoute
  AuthedPlacementsIndexRoute: typeof AuthedPlacementsIndexRoute
  AuthedRequestsIndexRoute: typeof AuthedRequestsIndexRoute
  AuthedReviewsIndexRoute: typeof AuthedReviewsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedApplicationsApplicationIdRoute: AuthedApplicationsApplicationIdRoute,
  AuthedApprenticesApprenticeIdRoute: AuthedApprenticesApprenticeIdRoute,
  AuthedPlacementsPlacementIdRoute: AuthedPlacementsPlacementIdRoute,
  AuthedPlacementsNewRoute: AuthedPlacementsNewRoute,
  AuthedRequestsNewRoute: AuthedRequestsNewRoute,
  AuthedReviewsNewRoute: AuthedReviewsNewRoute,
  AuthedApplicationsIndexRoute: AuthedApplicationsIndexRoute,
  AuthedApprenticesIndexRoute: AuthedApprenticesIndexRoute,
  AuthedManagersIndexRoute: AuthedManagersIndexRoute,
  AuthedPlacementsIndexRoute: AuthedPlacementsIndexRoute,
  AuthedRequestsIndexRoute: AuthedRequestsIndexRoute,
  AuthedReviewsIndexRoute: AuthedReviewsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
